from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, DateTime

from sqlalchemy.orm import relationship

from datetime import datetime

from .db import Base


# CREATE TABLE "Users" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "email" varchar(50) NOT NULL,
#   "password" varchar(100) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
class Users(Base):
    __tablename__ = "Users"

    id = Column(Integer, primary_key=True)
    email = Column(String(50), unique=True, nullable=False)
    password = Column(String(50), nullable=False)
    created_at = Column(DateTime, default=datetime.now())
    deleted = Column(Boolean, default=False)
# CREATE TABLE "Roles" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(20) NOT NULL,
#   "juridical" boolean DEFAULT false,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
class Roles(Base):
    __tablename__ = "Roles"

    id = Column(Integer, primary_key=True)
    title = Column(String(20), nullable=False)
    juridical = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.now())
    deleted = Column(Boolean, default=False)
# CREATE TABLE "UsersRoles" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "user_id" int NOT NULL,
#   "role_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
class UsersRoles(Base):
    __tablename__ = "UsersRoles"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('Users.id'), nullable=False)
    role_id = Column(Integer, ForeignKey('Roles.id'), nullable=False)
    created_at = Column(DateTime, default=datetime.now())
    deleted = Column(Boolean, default=False)

    user = relationship('Users', backref='users_roles')
    role = relationship('Roles', backref='users_roles')
# CREATE TABLE "UsersInfo" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "user_id" int NOT NULL,
#   "first_name" varchar(20) NOT NULL,
#   "second_name" varchar(20) NOT NULL,
#   "surname" varchar(20) NOT NULL,
#   "email" varchar(50) NOT NULL,
#   "phone" varchar(15) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
# ForeignKey('Users.id')

# CREATE TABLE "JuridicalUsers" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "user_id" int NOT NULL,
#   "position" varchar(20) NOT NULL,
#   "title" varchar(100) NOT NULL,
#   "inn" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "TenantUsers" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "user_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "LandlordUsers" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "user_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "AdminUsers" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "user_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Industry" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(50) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Photos" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "src" varchar(50) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Metro" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(30) NOT NULL,
#   "color" varchar(10) NOT NULL,
#   "branch" varchar(20) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Equipments" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(40) NOT NULL,
#   "price" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Accessibilities" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(255) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Facilities" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(255) NOT NULL,
#   "price" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Platforms" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "title" varchar(50) NOT NULL,
#   "description" varchar(255) NOT NULL,
#   "capacity" int NOT NULL,
#   "verified" boolean NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "MetroEquipments" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "metro_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsEquipments" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "equipment_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsIndustry" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "industry_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsPhotos" (
#   "id" int NOT NULL,
#   "platform_id" int NOT NULL,
#   "photo_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsAccessibilities" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "accessibility_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsFacilities" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "facility_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsWorkingHours" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "from_time" timestamp NOT NULL,
#   "to_time" timestamp NOT NULL,
#   "time_slot" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsBusySlots" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "from_time" timestamp NOT NULL,
#   "to_time" timestamp NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Bookings" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "tenant_id" int NOT NULL,
#   "landlord_id" int NOT NULL,
#   "plaform_id" int NOT NULL,
#   "time_slot_id" int NOT NULL,
#   "payed" boolean NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "Contracts" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "src" varchar(50) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "BookingContracts" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "contract_id" int NOT NULL,
#   "booking_id" int NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
# CREATE TABLE "PlatformsReviews" (
#   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   "platform_id" int NOT NULL,
#   "tenant_id" int NOT NULL,
#   "review" varchar(255) NOT NULL,
#   "created_at" timestamp DEFAULT (now()),
#   "deleted" boolean DEFAULT false
# );
#
